services:
  backend:
    container_name: romeomihail_backend
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile.dev}
    ports:
      - "${BACKEND_PORT:-8080}:8000"
    networks:
      - romeomihail_network
    env_file:
      - .env
    volumes:
      - .:/app
      - ./volumes/static:/app/staticfiles
      - ./volumes/media:/app/media
    healthcheck:
      test: ["CMD", "python", "manage.py", "check", "--database", "default"]
      interval: 50s
      timeout: 3s
      retries: 3
      start_period: 20s
    depends_on:
      rm_db:
        condition: service_healthy
    restart: unless-stopped

  rm_db:
    image: postgres:18-alpine
    container_name: romeomihail_db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-romeomihail_db}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT:-5433}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - ./volumes/postgres:/var/lib/postgresql
    networks:
      - romeomihail_network
    restart: unless-stopped

  rm_pgadmin:
    image: dpage/pgadmin4
    container_name: romeomihail_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_MFA_SUPPORTED_METHODS: '["authenticator"]'
      PGADMIN_CONFIG_MFA_FORCE_REGISTRATION: "True"
    ports:
      - "5051:80"
    networks:
      - romeomihail_network
    depends_on:
      - rm_db
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin
    restart: unless-stopped

  # Production only services
  certbot:
    profiles: ["prod"]
    image: certbot/certbot
    container_name: romeomihail_certbot
    volumes:
      - ./ssl:/etc/letsencrypt
      - ./certbot-webroot:/var/www/certbot
    entrypoint: |
      /bin/sh -c '
        trap exit TERM;
        while :; do
          certbot renew --webroot --webroot-path=/var/www/certbot;
          sleep 12h & wait $${!};
        done
      '
    restart: unless-stopped

networks:
  romeomihail_network:
    driver: bridge
    name: romeomihail_network